# Generated by Django 5.1.2 on 2024-11-17 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo_nome', models.CharField(max_length=30)),
                ('veiculo_ofplaca', models.CharField(max_length=9)),
                ('veiculo_instalplaca', models.CharField(max_length=9)),
                ('veiculo_cartao', models.CharField(max_length=16)),
                ('veiculo_revinterval', models.IntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisao_data', models.DateTimeField(verbose_name='data published')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appfrota.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viagem_destino', models.CharField(max_length=200)),
                ('viagem_datasaida', models.DateTimeField(verbose_name='data published')),
                ('viagem_kmsaida', models.IntegerField(default=0)),
                ('viagem_dataret', models.DateTimeField(verbose_name='data published')),
                ('viagem_kmret', models.IntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appfrota.veiculo')),
            ],
        ),
    ]
