# Generated by Django 5.1.2 on 2024-12-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfrota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='veiculo_combust',
            field=models.IntegerField(default=12),
        ),
    ]
