# Generated by Django 5.1.2 on 2024-12-05 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfrota', '0002_veiculo_veiculo_combust'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo_combust', models.IntegerField(default=12)),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='appfrota.veiculo')),
            ],
        ),
    ]
